{% set theme_name = "tactile" %}
{% set name = '-'.join(['jekyll-theme', theme_name]) %}
{% set version = "0.2.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: b7861b48aed5b2385d7a146b13f31cb6f37afe3107f4a6b93b1c932b2d242652

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-jekyll >=3.5,<4.0
    - rb-jekyll-seo-tag >=2.0,<3

test:
  commands:
    - gem list -i {{ name }} -v {{ version }}

about:
  home: https://rubygems.org/gems/{{ name }}
  license: CC0-1.0
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Tactile is a Jekyll theme for GitHub Pages

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/pages-themes/{{ theme_name }}

extra:
  recipe-maintainers:
    - sodre
