travis:
  secure:
    BINSTAR_TOKEN: F6b40jmOiv7WdmmTtDg6ub6P3qiQwUd3i7YuGUkBzx/EyPFUbBfyJX09RhsOjh0pCR/5T2fMljPb+RlTBqaXFaJrpQ38Yl97QOkNmOhMySvch5kMs1DFGl/V2HBrOK+PI8zDHHzc5/3gG4Ll7ebkyCZm4ktYOI5b+EcB+BWMEJd9Xkc+VmjvS9WdS/r4BiPZ36RvqABXaso1Zqg9B/x1g/pPML8jQgaelP7YpfNklB/hTFnsKVjd8jQx/Jw2zJOxA0pBUbiR6mM5IOJcZz1IJmhjt/2fQwUEH2D8jAWqNGx20NZg6HNEy1td8FjaEqab5Kk+08DJ1eb2ciW0SgH4qPI2vum7mIpKtGKgWqsqNkrXjS92d/zJjOGwOG/2mn5HQQOkGF3DZpx6bHLdAiO6lBHJVKDubVoq0FYMZka/VwXn4KYshyk2pKG4SNzThRZiBBTpunSj6AG/tpaxJWM/7RVqJ8M7ZZIc0mwYs1zKQ9kSad/zjDSWavy6X5zHK+xHH6u/ByiP4viyRsHrpKzoi9qgF6qg0wmLQpHkd62En3qnf9GLptYUwH4VX8RftjAwTcdyrX2forIfQvSZv1GT8/ZxXiDrRk0s2375K8qUisoKVYLoDB+mj/B+KyXRiUTegsoIQHfEouw5z/OTFjRGz88D3oKC8DeamgvxLpPFFsA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
